Fix TypeError when calling executable scripts
Running one of the generated executable scripts would result in an
error message.

For example:

```
$ ppp --version
Traceback (most recent call last):
  File "/usr/bin/ppp", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/pypipe.py", line 836, in main
    if len(argv) == 0 or argv[0] not in expected_1st_args:
       ^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
```

That error seems to be caused by pip’s shim script calling the `main()`
function without arguments.

Fix this by setting the default value for the `argv` kwarg to
`sys.argv[1:]` in the signature of the `main` function.